// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieRatingAPI.Models;

namespace MovieRatingAPI.Migrations
{
    [DbContext(typeof(MovieContext))]
    [Migration("20210926181432_FirstMig")]
    partial class FirstMig
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("MovieRatingAPI.Models.Movies", b =>
                {
                    b.Property<decimal>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("ID");

                    b.Property<string>("Actors")
                        .HasColumnType("TEXT")
                        .HasColumnName("ACTORS");

                    b.Property<string>("Director")
                        .HasColumnType("TEXT")
                        .HasColumnName("DIRECTOR");

                    b.Property<byte[]>("Poster")
                        .HasColumnType("BLOB")
                        .HasColumnName("POSTER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT")
                        .HasColumnName("TITLE");

                    b.HasKey("Id");

                    b.ToTable("MOVIES");
                });
#pragma warning restore 612, 618
        }
    }
}
